import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import Card from "@/components/Cards/Card";
import { categories } from "@/data/categories.json";
import useCreatePlaylist from "@/hooks/useCreatePlaylist";
import SearchBar from "@/components/Inputs/SearchBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center bg-slate-800 ">
        <main className="container mx-auto px-4">
          <AuthShowcase />
          <SearchBar />
          <div>
            {categories.map((category) => (
              <>
                <h6 className="text-xl font-bold mb-4 text-white">
                  {category.title}
                </h6>
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 items-start mb-5">
                  {category.list.map((item) => (
                    <Card title={item} key={item} />
                  ))}
                </div>
              </>
            ))}
          </div>
        </main>
      </div>
    </>
  );
}

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const [createPlaylist, {}] = useCreatePlaylist();
  return (
    <main>
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Welcome, {sessionData.user?.name} !</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
      {sessionData && (
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={async () => await createPlaylist("TEST")}
        >
          TEST
        </button>
      )}
    </main>
  );
};
